---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-kdex-dev-v1alpha1-kdexapps
  failurePolicy: Fail
  name: kdexapps.kdex.dev
  rules:
  - apiGroups:
    - kdex.dev
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - kdexapps
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-kdex-dev-v1alpha1-kdexhosts
  failurePolicy: Fail
  name: kdexhosts.kdex.dev
  rules:
  - apiGroups:
    - kdex.dev
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - kdexhosts
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-kdex-dev-v1alpha1-kdexthemes
  failurePolicy: Fail
  name: kdexthemes.kdex.dev
  rules:
  - apiGroups:
    - kdex.dev
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - kdexthemes
  sideEffects: None
