---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-kdex-dev-v1alpha1-kdexapp
  failurePolicy: Ignore
  name: mutate.kdexapp.kdex.dev
  rules:
  - apiGroups:
    - kdex.dev
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - kdexapps
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-kdex-dev-v1alpha1-kdexclusterapp
  failurePolicy: Ignore
  name: mutate.kdexclusterapp.kdex.dev
  rules:
  - apiGroups:
    - kdex.dev
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - kdexclusterapps
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-kdex-dev-v1alpha1-kdexclusterpagearchetype
  failurePolicy: Ignore
  name: mutate.kdexclusterpagearchetype.kdex.dev
  rules:
  - apiGroups:
    - kdex.dev
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - kdexclusterpagearchetypes
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-kdex-dev-v1alpha1-kdexclusterpagefooter
  failurePolicy: Ignore
  name: mutate.kdexclusterpagefooter.kdex.dev
  rules:
  - apiGroups:
    - kdex.dev
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - kdexclusterpagefooters
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-kdex-dev-v1alpha1-kdexclusterpageheader
  failurePolicy: Ignore
  name: mutate.kdexclusterpageheader.kdex.dev
  rules:
  - apiGroups:
    - kdex.dev
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - kdexclusterpageheaders
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-kdex-dev-v1alpha1-kdexclusterpagenavigation
  failurePolicy: Ignore
  name: mutate.kdexclusterpagenavigation.kdex.dev
  rules:
  - apiGroups:
    - kdex.dev
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - kdexclusterpagenavigations
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-kdex-dev-v1alpha1-kdexclusterscriptlibrary
  failurePolicy: Ignore
  name: mutate.kdexclusterscriptlibrary.kdex.dev
  rules:
  - apiGroups:
    - kdex.dev
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - kdexclusterscriptlibraries
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-kdex-dev-v1alpha1-kdexclustertheme
  failurePolicy: Ignore
  name: mutate.kdexclustertheme.kdex.dev
  rules:
  - apiGroups:
    - kdex.dev
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - kdexclusterthemes
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-kdex-dev-v1alpha1-kdexclusterutilitypage
  failurePolicy: Ignore
  name: mutate.kdexclusterutilitypage.kdex.dev
  rules:
  - apiGroups:
    - kdex.dev
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - kdexclusterutilitypages
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-kdex-dev-v1alpha1-kdexfunction
  failurePolicy: Ignore
  name: mutate.kdexfunction.kdex.dev
  rules:
  - apiGroups:
    - kdex.dev
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - kdexfunctions
    - kdexfunctions/status
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-kdex-dev-v1alpha1-kdexhost
  failurePolicy: Ignore
  name: mutate.kdexhost.kdex.dev
  rules:
  - apiGroups:
    - kdex.dev
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - kdexhosts
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-kdex-dev-v1alpha1-kdexpagearchetype
  failurePolicy: Ignore
  name: mutate.kdexpagearchetype.kdex.dev
  rules:
  - apiGroups:
    - kdex.dev
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - kdexpagearchetypes
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-kdex-dev-v1alpha1-kdexpagebinding
  failurePolicy: Ignore
  name: mutate.kdexpagebinding.kdex.dev
  rules:
  - apiGroups:
    - kdex.dev
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - kdexpagebindings
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-kdex-dev-v1alpha1-kdexpagefooter
  failurePolicy: Ignore
  name: mutate.kdexpagefooter.kdex.dev
  rules:
  - apiGroups:
    - kdex.dev
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - kdexpagefooters
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-kdex-dev-v1alpha1-kdexpageheader
  failurePolicy: Ignore
  name: mutate.kdexpageheader.kdex.dev
  rules:
  - apiGroups:
    - kdex.dev
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - kdexpageheaders
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-kdex-dev-v1alpha1-kdexpagenavigation
  failurePolicy: Ignore
  name: mutate.kdexpagenavigation.kdex.dev
  rules:
  - apiGroups:
    - kdex.dev
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - kdexpagenavigations
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-kdex-dev-v1alpha1-kdexscriptlibrary
  failurePolicy: Ignore
  name: mutate.kdexscriptlibrary.kdex.dev
  rules:
  - apiGroups:
    - kdex.dev
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - kdexscriptlibraries
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-kdex-dev-v1alpha1-kdextheme
  failurePolicy: Ignore
  name: mutate.kdextheme.kdex.dev
  rules:
  - apiGroups:
    - kdex.dev
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - kdexthemes
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-kdex-dev-v1alpha1-kdexutilitypage
  failurePolicy: Ignore
  name: mutate.kdexutilitypage.kdex.dev
  rules:
  - apiGroups:
    - kdex.dev
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - kdexutilitypages
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-kdex-dev-v1alpha1-kdexapp
  failurePolicy: Ignore
  name: validate.kdexapp.kdex.dev
  rules:
  - apiGroups:
    - kdex.dev
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - kdexapps
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-kdex-dev-v1alpha1-kdexclusterapp
  failurePolicy: Ignore
  name: validate.kdexclusterapp.kdex.dev
  rules:
  - apiGroups:
    - kdex.dev
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - kdexclusterapps
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-kdex-dev-v1alpha1-kdexclusterscriptlibrary
  failurePolicy: Ignore
  name: validate.kdexclusterscriptlibrary.kdex.dev
  rules:
  - apiGroups:
    - kdex.dev
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - kdexclusterscriptlibraries
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-kdex-dev-v1alpha1-kdexclustertheme
  failurePolicy: Ignore
  name: validate.kdexclustertheme.kdex.dev
  rules:
  - apiGroups:
    - kdex.dev
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - kdexclusterthemes
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-kdex-dev-v1alpha1-kdexclustertranslation
  failurePolicy: Ignore
  name: validate.kdexclustertranslation.kdex.dev
  rules:
  - apiGroups:
    - kdex.dev
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - kdexclustertranslations
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-kdex-dev-v1alpha1-kdexclusterutilitypage
  failurePolicy: Ignore
  name: validate.kdexclusterutilitypage.kdex.dev
  rules:
  - apiGroups:
    - kdex.dev
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - kdexclusterutilitypages
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-kdex-dev-v1alpha1-kdexfunction
  failurePolicy: Ignore
  name: validate.kdexfunction.kdex.dev
  rules:
  - apiGroups:
    - kdex.dev
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - kdexfunctions
    - kdexfunctions/status
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-kdex-dev-v1alpha1-kdexhost
  failurePolicy: Ignore
  name: validate.kdexhost.kdex.dev
  rules:
  - apiGroups:
    - kdex.dev
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - kdexhosts
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-kdex-dev-v1alpha1-kdexpagebinding
  failurePolicy: Ignore
  name: validate.kdexpagebinding.kdex.dev
  rules:
  - apiGroups:
    - kdex.dev
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - kdexpagebindings
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-kdex-dev-v1alpha1-kdexscriptlibrary
  failurePolicy: Ignore
  name: validate.kdexscriptlibrary.kdex.dev
  rules:
  - apiGroups:
    - kdex.dev
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - kdexscriptlibraries
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-kdex-dev-v1alpha1-kdextheme
  failurePolicy: Ignore
  name: validate.kdextheme.kdex.dev
  rules:
  - apiGroups:
    - kdex.dev
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - kdexthemes
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-kdex-dev-v1alpha1-kdextranslation
  failurePolicy: Ignore
  name: validate.kdextranslation.kdex.dev
  rules:
  - apiGroups:
    - kdex.dev
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - kdextranslations
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-kdex-dev-v1alpha1-kdexutilitypage
  failurePolicy: Ignore
  name: validate.kdexutilitypage.kdex.dev
  rules:
  - apiGroups:
    - kdex.dev
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - kdexutilitypages
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-kdex-dev-v1alpha1-kdexclusterpagearchetype
  failurePolicy: Ignore
  name: validation.kdexclusterpagearchetype.kdex.dev
  rules:
  - apiGroups:
    - kdex.dev
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - kdexclusterpagearchetypes
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-kdex-dev-v1alpha1-kdexclusterpagefooter
  failurePolicy: Ignore
  name: validation.kdexclusterpagefooter.kdex.dev
  rules:
  - apiGroups:
    - kdex.dev
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - kdexclusterpagefooters
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-kdex-dev-v1alpha1-kdexclusterpageheader
  failurePolicy: Ignore
  name: validation.kdexclusterpageheader.kdex.dev
  rules:
  - apiGroups:
    - kdex.dev
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - kdexclusterpageheaders
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-kdex-dev-v1alpha1-kdexclusterpagenavigation
  failurePolicy: Ignore
  name: validation.kdexclusterpagenavigation.kdex.dev
  rules:
  - apiGroups:
    - kdex.dev
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - kdexclusterpagenavigations
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-kdex-dev-v1alpha1-kdexpagearchetype
  failurePolicy: Ignore
  name: validation.kdexpagearchetype.kdex.dev
  rules:
  - apiGroups:
    - kdex.dev
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - kdexpagearchetypes
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-kdex-dev-v1alpha1-kdexpagefooter
  failurePolicy: Ignore
  name: validation.kdexpagefooter.kdex.dev
  rules:
  - apiGroups:
    - kdex.dev
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - kdexpagefooters
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-kdex-dev-v1alpha1-kdexpageheader
  failurePolicy: Ignore
  name: validation.kdexpageheader.kdex.dev
  rules:
  - apiGroups:
    - kdex.dev
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - kdexpageheaders
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-kdex-dev-v1alpha1-kdexpagenavigation
  failurePolicy: Ignore
  name: validation.kdexpagenavigation.kdex.dev
  rules:
  - apiGroups:
    - kdex.dev
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - kdexpagenavigations
  sideEffects: None
