---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kdex.dev
  resources:
  - kdexapps
  - kdexhostcontrollers
  - kdexhosts
  - kdexpagearchetypes
  - kdexpagebindings
  - kdexpagefooters
  - kdexpageheaders
  - kdexpagenavigations
  - kdexscriptlibraries
  - kdexthemes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kdex.dev
  resources:
  - kdexapps/finalizers
  - kdexhosts/finalizers
  - kdexpagearchetypes/finalizers
  - kdexpagebindings/finalizers
  - kdexpagefooters/finalizers
  - kdexpageheaders/finalizers
  - kdexpagenavigations/finalizers
  - kdexscriptlibraries/finalizers
  - kdexthemes/finalizers
  verbs:
  - update
- apiGroups:
  - kdex.dev
  resources:
  - kdexapps/status
  - kdexhosts/status
  - kdexpagearchetypes/status
  - kdexpagebindings/status
  - kdexpagefooters/status
  - kdexpageheaders/status
  - kdexpagenavigations/status
  - kdexscriptlibraries/status
  - kdexthemes/status
  verbs:
  - get
  - patch
  - update
