apiVersion: kdex.dev/v1alpha1
kind: KDexClusterPageFooter
metadata:
  labels:
    control-plane: controller-manager
    app.kubernetes.io/name: kdex-nexus
    app.kubernetes.io/managed-by: kustomize
  name: kdex-default-page-footer
spec:
  content: |
    <div>
      <small>&copy; {{ .LastModified.Year }} {{ .Organization }} {{ l10n "all-rights-reserved" }}</small>
    </div>
