apiVersion: kdex.dev/v1alpha1
kind: KDexClusterPageArchetype
metadata:
  name: kdex-default-page-archetype-utility
spec:
  content: |
    <!DOCTYPE html>
    <html lang="{{ .Language }}">
      <head>
        {{ .Meta }}
        <title>{{l10n .BrandName}}</title>
        {{ .Theme }}
      </head>
      <body class="utility-page">
        <main>
          {{ .Content.main }}
        </main>
      </body>
    </html>
