apiVersion: kdex.dev/v1alpha1
kind: KDexClusterPageHeader
metadata:
  labels:
    control-plane: controller-manager
    app.kubernetes.io/name: kdex-nexus
    app.kubernetes.io/managed-by: kustomize
  name: kdex-default-page-header
spec:
  content: |
    <div>
      <div>
        <div>
          <nav id="navigation-header">
            <a href="/">
              <img alt="{{ l10n .BrandName }}">
            </a>
            <a href="/">
              {{ l10n .BrandName }}
            </a>
          </nav>
          {{ .Navigation.language }}
        </div>
      </div>
    </div>
