apiVersion: kdex.dev/v1alpha1
kind: KDexClusterPageHeader
metadata:
  name: kdex-default-page-header
spec:
  content: |
    <header class="page-header">
      <div>
        <nav id="page-brand">
          <a class="page-logo" href="/">
            <img alt="{{ l10n .BrandName }}">
          </a>
          <a class="page-brand-name" href="/">
            {{ l10n .BrandName }}
          </a>
        </nav>
        {{ pop .Navigation "language" }}
      </div>
    </header>
