apiVersion: kdex.dev/v1alpha1
kind: KDexClusterPageFooter
metadata:
  name: kdex-default-page-footer
spec:
  content: |
    <div>
      <small>&copy; {{ .LastModified.Year }} {{ .Organization }} {{ l10n "all-rights-reserved" }}</small>
    </div>
