apiVersion: kdex.dev/v1alpha1
kind: KDexClusterPageArchetype
metadata:
  name: kdex-default-page-archetype-standard
spec:
  content: |
    <!DOCTYPE html>
    <html lang="{{ .Language }}">
      <head>
        {{ .Meta }}
        <title>{{ l10n .Title }}</title>
        {{ .Theme }}
        {{ .HeadScript }}
      </head>
      <body>
        <header>
          {{ .Header }}
        </header>
        <nav>
          {{/* use 'pop' to both render a slot in place and remove it from the Navigation map */}}
          {{ pop .Navigation "main" }}
        </nav>
        <main>
          {{/* use 'pop' to both render a slot in place and remove it from the Content map */}}
          {{ pop .Content "main" }}
        </main>
        <footer>
          {{ .Footer }}
        </footer>
        {{ .FootScript }}

        {{/* render any remaining slots in the Content map as HTML templates */}}
        {{- range $slot, $content := .Content }}
          <template id="content-{{ $slot }}">
            {{ $content }}
          </template>
        {{- end -}}

        {{/* render any remaining slots in the Navigation map as HTML templates */}}
        {{- range $slot, $content := .Navigation }}
          <template id="navigation-{{ $slot }}">
            {{ $content }}
          </template>
        {{- end -}}
      </body>
    </html>
  defaultFooterRef:
    kind: KDexClusterPageFooter
    name: kdex-default-page-footer
  defaultHeaderRef:
    kind: KDexClusterPageHeader
    name: kdex-default-page-header
  defaultMainNavigationRef:
    kind: KDexClusterPageNavigation
    name: kdex-default-page-navigation-main
  extraNavigations:
    language:
      kind: KDexClusterPageNavigation
      name: kdex-default-page-navigation-language
  scriptLibraryRef:
    kind: KDexClusterScriptLibrary
    name: kdex-default-script-library
