apiVersion: kdex.dev/v1alpha1
kind: KDexClusterPageHeader
metadata:
  name: kdex-default-page-header
spec:
  content: |
    <style>
      .header-actions {
        display: flex;
        align-items: center;
        gap: 1.5rem;
      }
    </style>
    <header class="page-header">
      <div>
        <nav id="page-brand">
          <a class="page-logo" href="/">
            <img alt="{{ l10n .BrandName }}">
          </a>
          <a class="page-brand-name" href="/">
            {{ l10n .BrandName }}
          </a>
        </nav>
        <div class="header-actions">
          {{ pop .Navigation "language" }}
          {{ pop .Navigation "login" }}
        </div>
      </div>
    </header>
