apiVersion: kdex.dev/v1alpha1
kind: KDexClusterPageNavigation
metadata:
  name: kdex-default-page-navigation-login
spec:
  content: |
    <ul class="navigation login-status">
    {{- if .Extra.Identity -}}
      <li class="navigation user-profile dropdown">
        <div class="user-trigger">
          <div class="user-avatar">
            {{- if .Extra.Identity.Picture -}}
              <img src="{{ .Extra.Identity.Picture }}" alt="{{ .Extra.Identity.Email }}" class="avatar-image">
            {{- else -}}
              <div class="avatar-initials">
                {{- if .Extra.Identity.GivenName -}}
                  {{ .Extra.Identity.GivenName | trunc 1 | upper }}{{ if .Extra.Identity.FamilyName }}{{ .Extra.Identity.FamilyName | trunc 1 | upper }}{{ end }}
                {{- else -}}
                  {{ .Extra.Identity.Email | default (.Extra.Identity.UID | default "U") | trunc 2 | upper }}
                {{- end -}}
              </div>
            {{- end -}}
          </div>
          <div class="user-info">
            <span class="user-name">
              {{- .Extra.Identity.Nickname | default (.Extra.Identity.Name | default (.Extra.Identity.Email | default (.Extra.Identity.UID | default "User"))) -}}
            </span>
          </div>
        </div>
        <div class="dropdown-content">
           <div class="dropdown-header">
             <div class="user-name" style="font-weight: 600;">{{ .Extra.Identity.Name | default (.Extra.Identity.Email | default .Extra.Identity.UID) }}</div>
             <div class="header-email">{{ .Extra.Identity.Email }}</div>
           </div>
           <form action="/~/logout" method="POST" id="logout-form">
              <button type="submit" class="logout-button">
                 Logout
              </button>
           </form>
        </div>
      </li>
    {{- else -}}
      <li class="navigation login-link">
        <a href="/~/login" class="login-button">
          {{ l10n "login.signin" }}
        </a>
      </li>
    {{- end -}}
    </ul>
