apiVersion: kdex.dev/v1alpha1
kind: KDexClusterUtilityPage
metadata:
  name: kdex-default-utility-page-error
spec:
  contentEntries:
  - rawHTML: |
      <div class="error-container">
        <strong>{{ l10n "error.title" .BrandName }}</strong>

        <h2>{{ .Extra.ErrorCode }}: {{ l10n .Extra.ErrorCodeString }}</h2>

        <p class="error-label">{{l10n "error.label"}}</p>
        <code class="error-message">{{ .Extra.ErrorMessage }}</code>

        <div class="footer">
            <p>{{l10n "announcement.organization" .Organization}}</p>
        </div>
      </div>
    slot: main
  pageArchetypeRef:
    kind: KDexClusterPageArchetype
    name: kdex-default-page-archetype-utility
  type: Error
