nameReference:
- group: kdex.dev
  version: v1alpha1
  kind: KDexClusterPageArchetype
  skip: true
- group: kdex.dev
  version: v1alpha1
  kind: KDexClusterPageFooter
  skip: true
- group: kdex.dev
  version: v1alpha1
  kind: KDexClusterPageHeader
  skip: true
- group: kdex.dev
  version: v1alpha1
  kind: KDexClusterPageNavigation
  skip: true
- group: kdex.dev
  version: v1alpha1
  kind: KDexClusterScriptLibrary
  skip: true
- group: kdex.dev
  version: v1alpha1
  kind: KDexClusterUtilityPage
  skip: true
